# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 725)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pbUp = QtWidgets.QPushButton(self.centralwidget)
        self.pbUp.setGeometry(QtCore.QRect(660, 580, 75, 23))
        self.pbUp.setObjectName("pbUp")
        self.pbDown = QtWidgets.QPushButton(self.centralwidget)
        self.pbDown.setGeometry(QtCore.QRect(660, 540, 75, 23))
        self.pbDown.setObjectName("pbDown")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 450, 371, 192))
        self.tableWidget.setRowCount(100)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.verticalHeader().setDefaultSectionSize(26)
        self.tabJogging = QtWidgets.QTabWidget(self.centralwidget)
        self.tabJogging.setGeometry(QtCore.QRect(500, 20, 281, 351))
        self.tabJogging.setObjectName("tabJogging")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.lblAngSpeedValue = QtWidgets.QLabel(self.tab_1)
        self.lblAngSpeedValue.setGeometry(QtCore.QRect(140, 10, 21, 20))
        self.lblAngSpeedValue.setObjectName("lblAngSpeedValue")
        self.lblAngSpeed = QtWidgets.QLabel(self.tab_1)
        self.lblAngSpeed.setGeometry(QtCore.QRect(40, 10, 91, 20))
        self.lblAngSpeed.setObjectName("lblAngSpeed")
        self.sldAngSpeedValue = QtWidgets.QSlider(self.tab_1)
        self.sldAngSpeedValue.setGeometry(QtCore.QRect(20, 30, 241, 22))
        self.sldAngSpeedValue.setOrientation(QtCore.Qt.Horizontal)
        self.sldAngSpeedValue.setObjectName("sldAngSpeedValue")
        self.lblAngIncDec = QtWidgets.QLabel(self.tab_1)
        self.lblAngIncDec.setGeometry(QtCore.QRect(35, 270, 120, 20))
        self.lblAngIncDec.setObjectName("lblAngIncDec")
        self.sldAngIncDecValue = QtWidgets.QSlider(self.tab_1)
        self.sldAngIncDecValue.setGeometry(QtCore.QRect(20, 290, 251, 22))
        self.sldAngIncDecValue.setMinimum(1)
        self.sldAngIncDecValue.setMaximum(45)
        self.sldAngIncDecValue.setOrientation(QtCore.Qt.Horizontal)
        self.sldAngIncDecValue.setObjectName("sldAngIncDecValue")
        self.lblAngIncDecValue = QtWidgets.QLabel(self.tab_1)
        self.lblAngIncDecValue.setGeometry(QtCore.QRect(160, 270, 21, 20))
        self.lblAngIncDecValue.setObjectName("lblAngIncDecValue")
        self.lEditAngle6 = QtWidgets.QLineEdit(self.tab_1)
        self.lEditAngle6.setGeometry(QtCore.QRect(20, 230, 50, 21))
        self.lEditAngle6.setObjectName("lEditAngle6")
        self.pbTheta2_dec = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta2_dec.setGeometry(QtCore.QRect(200, 90, 50, 23))
        self.pbTheta2_dec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta2_dec.setObjectName("pbTheta2_dec")
        self.lEditAngle1 = QtWidgets.QLineEdit(self.tab_1)
        self.lEditAngle1.setGeometry(QtCore.QRect(20, 60, 50, 23))
        self.lEditAngle1.setObjectName("lEditAngle1")
        self.lEditAngle5 = QtWidgets.QLineEdit(self.tab_1)
        self.lEditAngle5.setGeometry(QtCore.QRect(20, 200, 50, 23))
        self.lEditAngle5.setObjectName("lEditAngle5")
        self.pbTheta1_inc = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta1_inc.setGeometry(QtCore.QRect(140, 60, 50, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbTheta1_inc.sizePolicy().hasHeightForWidth())
        self.pbTheta1_inc.setSizePolicy(sizePolicy)
        self.pbTheta1_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta1_inc.setObjectName("pbTheta1_inc")
        self.lEditAngle4 = QtWidgets.QLineEdit(self.tab_1)
        self.lEditAngle4.setGeometry(QtCore.QRect(20, 170, 50, 23))
        self.lEditAngle4.setObjectName("lEditAngle4")
        self.pbTheta3_inc = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta3_inc.setGeometry(QtCore.QRect(140, 120, 50, 23))
        self.pbTheta3_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta3_inc.setObjectName("pbTheta3_inc")
        self.lEditAngle3 = QtWidgets.QLineEdit(self.tab_1)
        self.lEditAngle3.setGeometry(QtCore.QRect(20, 120, 50, 23))
        self.lEditAngle3.setObjectName("lEditAngle3")
        self.lEditAngle2 = QtWidgets.QLineEdit(self.tab_1)
        self.lEditAngle2.setGeometry(QtCore.QRect(20, 90, 50, 23))
        self.lEditAngle2.setObjectName("lEditAngle2")
        self.pbTheta4_inc = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta4_inc.setGeometry(QtCore.QRect(140, 170, 50, 23))
        self.pbTheta4_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta4_inc.setObjectName("pbTheta4_inc")
        self.pbTheta6_dec = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta6_dec.setGeometry(QtCore.QRect(200, 230, 50, 23))
        self.pbTheta6_dec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta6_dec.setObjectName("pbTheta6_dec")
        self.pbTheta3_dec = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta3_dec.setGeometry(QtCore.QRect(200, 120, 50, 23))
        self.pbTheta3_dec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta3_dec.setObjectName("pbTheta3_dec")
        self.pbTheta6_inc = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta6_inc.setGeometry(QtCore.QRect(140, 230, 50, 23))
        self.pbTheta6_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta6_inc.setObjectName("pbTheta6_inc")
        self.pbTheta2_inc = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta2_inc.setGeometry(QtCore.QRect(140, 90, 50, 23))
        self.pbTheta2_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta2_inc.setObjectName("pbTheta2_inc")
        self.pbTheta1_dec = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta1_dec.setGeometry(QtCore.QRect(200, 60, 50, 23))
        self.pbTheta1_dec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta1_dec.setObjectName("pbTheta1_dec")
        self.pbTheta4_dec = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta4_dec.setGeometry(QtCore.QRect(200, 170, 50, 23))
        self.pbTheta4_dec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta4_dec.setObjectName("pbTheta4_dec")
        self.pbTheta5_dec = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta5_dec.setGeometry(QtCore.QRect(200, 200, 50, 23))
        self.pbTheta5_dec.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta5_dec.setObjectName("pbTheta5_dec")
        self.pbTheta5_inc = QtWidgets.QPushButton(self.tab_1)
        self.pbTheta5_inc.setGeometry(QtCore.QRect(140, 200, 50, 23))
        self.pbTheta5_inc.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbTheta5_inc.setObjectName("pbTheta5_inc")
        self.lbl_t6 = QtWidgets.QLabel(self.tab_1)
        self.lbl_t6.setGeometry(QtCore.QRect(110, 230, 20, 23))
        self.lbl_t6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_t6.setObjectName("lbl_t6")
        self.lbl_t3 = QtWidgets.QLabel(self.tab_1)
        self.lbl_t3.setGeometry(QtCore.QRect(110, 120, 20, 23))
        self.lbl_t3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_t3.setObjectName("lbl_t3")
        self.lbl_t4 = QtWidgets.QLabel(self.tab_1)
        self.lbl_t4.setGeometry(QtCore.QRect(110, 170, 20, 23))
        self.lbl_t4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_t4.setObjectName("lbl_t4")
        self.lbl_t2 = QtWidgets.QLabel(self.tab_1)
        self.lbl_t2.setGeometry(QtCore.QRect(110, 90, 20, 23))
        self.lbl_t2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_t2.setObjectName("lbl_t2")
        self.lbl_t1 = QtWidgets.QLabel(self.tab_1)
        self.lbl_t1.setGeometry(QtCore.QRect(110, 60, 20, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_t1.sizePolicy().hasHeightForWidth())
        self.lbl_t1.setSizePolicy(sizePolicy)
        self.lbl_t1.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_t1.setObjectName("lbl_t1")
        self.lbl_t5 = QtWidgets.QLabel(self.tab_1)
        self.lbl_t5.setGeometry(QtCore.QRect(110, 200, 20, 23))
        self.lbl_t5.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_t5.setObjectName("lbl_t5")
        self.tabJogging.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lEditCart6 = QtWidgets.QLineEdit(self.tab_2)
        self.lEditCart6.setGeometry(QtCore.QRect(20, 230, 50, 23))
        self.lEditCart6.setObjectName("lEditCart6")
        self.lEditCart1 = QtWidgets.QLineEdit(self.tab_2)
        self.lEditCart1.setGeometry(QtCore.QRect(20, 60, 50, 23))
        self.lEditCart1.setObjectName("lEditCart1")
        self.lEditCart4 = QtWidgets.QLineEdit(self.tab_2)
        self.lEditCart4.setGeometry(QtCore.QRect(20, 170, 50, 23))
        self.lEditCart4.setObjectName("lEditCart4")
        self.lEditCart3 = QtWidgets.QLineEdit(self.tab_2)
        self.lEditCart3.setGeometry(QtCore.QRect(20, 120, 50, 23))
        self.lEditCart3.setObjectName("lEditCart3")
        self.lEditCart2 = QtWidgets.QLineEdit(self.tab_2)
        self.lEditCart2.setGeometry(QtCore.QRect(20, 90, 50, 23))
        self.lEditCart2.setObjectName("lEditCart2")
        self.lEditCart5 = QtWidgets.QLineEdit(self.tab_2)
        self.lEditCart5.setGeometry(QtCore.QRect(20, 200, 50, 23))
        self.lEditCart5.setObjectName("lEditCart5")
        self.lbl_z = QtWidgets.QLabel(self.tab_2)
        self.lbl_z.setGeometry(QtCore.QRect(110, 226, 20, 23))
        self.lbl_z.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_z.setObjectName("lbl_z")
        self.lbl_x = QtWidgets.QLabel(self.tab_2)
        self.lbl_x.setGeometry(QtCore.QRect(110, 170, 20, 23))
        self.lbl_x.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_x.setObjectName("lbl_x")
        self.lbl_Y = QtWidgets.QLabel(self.tab_2)
        self.lbl_Y.setGeometry(QtCore.QRect(110, 90, 20, 23))
        self.lbl_Y.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_Y.setObjectName("lbl_Y")
        self.lbl_y = QtWidgets.QLabel(self.tab_2)
        self.lbl_y.setGeometry(QtCore.QRect(110, 200, 20, 23))
        self.lbl_y.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_y.setObjectName("lbl_y")
        self.lbl_X = QtWidgets.QLabel(self.tab_2)
        self.lbl_X.setGeometry(QtCore.QRect(110, 60, 20, 23))
        self.lbl_X.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_X.setObjectName("lbl_X")
        self.lbl_Z = QtWidgets.QLabel(self.tab_2)
        self.lbl_Z.setGeometry(QtCore.QRect(110, 120, 20, 23))
        self.lbl_Z.setMaximumSize(QtCore.QSize(20, 16777215))
        self.lbl_Z.setObjectName("lbl_Z")
        self.pbCart6_inc = QtWidgets.QPushButton(self.tab_2)
        self.pbCart6_inc.setGeometry(QtCore.QRect(140, 230, 50, 23))
        self.pbCart6_inc.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart6_inc.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart6_inc.setObjectName("pbCart6_inc")
        self.pbCart2_inc = QtWidgets.QPushButton(self.tab_2)
        self.pbCart2_inc.setGeometry(QtCore.QRect(140, 90, 50, 23))
        self.pbCart2_inc.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart2_inc.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart2_inc.setObjectName("pbCart2_inc")
        self.pbCart1_inc = QtWidgets.QPushButton(self.tab_2)
        self.pbCart1_inc.setGeometry(QtCore.QRect(140, 60, 50, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbCart1_inc.sizePolicy().hasHeightForWidth())
        self.pbCart1_inc.setSizePolicy(sizePolicy)
        self.pbCart1_inc.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart1_inc.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart1_inc.setObjectName("pbCart1_inc")
        self.pbCart3_inc = QtWidgets.QPushButton(self.tab_2)
        self.pbCart3_inc.setGeometry(QtCore.QRect(140, 120, 50, 23))
        self.pbCart3_inc.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart3_inc.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart3_inc.setObjectName("pbCart3_inc")
        self.pbCart4_inc = QtWidgets.QPushButton(self.tab_2)
        self.pbCart4_inc.setGeometry(QtCore.QRect(140, 170, 50, 23))
        self.pbCart4_inc.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart4_inc.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart4_inc.setObjectName("pbCart4_inc")
        self.pbCart5_inc = QtWidgets.QPushButton(self.tab_2)
        self.pbCart5_inc.setGeometry(QtCore.QRect(140, 200, 50, 23))
        self.pbCart5_inc.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart5_inc.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart5_inc.setObjectName("pbCart5_inc")
        self.pbCart6_dec = QtWidgets.QPushButton(self.tab_2)
        self.pbCart6_dec.setGeometry(QtCore.QRect(200, 230, 50, 23))
        self.pbCart6_dec.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart6_dec.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart6_dec.setObjectName("pbCart6_dec")
        self.pbCart5_dec = QtWidgets.QPushButton(self.tab_2)
        self.pbCart5_dec.setGeometry(QtCore.QRect(200, 200, 50, 23))
        self.pbCart5_dec.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart5_dec.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart5_dec.setObjectName("pbCart5_dec")
        self.pbCart3_dec = QtWidgets.QPushButton(self.tab_2)
        self.pbCart3_dec.setGeometry(QtCore.QRect(200, 120, 50, 23))
        self.pbCart3_dec.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart3_dec.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart3_dec.setObjectName("pbCart3_dec")
        self.pbCart1_dec = QtWidgets.QPushButton(self.tab_2)
        self.pbCart1_dec.setGeometry(QtCore.QRect(200, 60, 50, 23))
        self.pbCart1_dec.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart1_dec.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart1_dec.setObjectName("pbCart1_dec")
        self.pbCart2_dec = QtWidgets.QPushButton(self.tab_2)
        self.pbCart2_dec.setGeometry(QtCore.QRect(200, 90, 50, 23))
        self.pbCart2_dec.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart2_dec.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart2_dec.setObjectName("pbCart2_dec")
        self.pbCart4_dec = QtWidgets.QPushButton(self.tab_2)
        self.pbCart4_dec.setGeometry(QtCore.QRect(200, 170, 50, 23))
        self.pbCart4_dec.setMinimumSize(QtCore.QSize(50, 0))
        self.pbCart4_dec.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pbCart4_dec.setObjectName("pbCart4_dec")
        self.sldCartSpeedValue = QtWidgets.QSlider(self.tab_2)
        self.sldCartSpeedValue.setGeometry(QtCore.QRect(20, 30, 241, 22))
        self.sldCartSpeedValue.setMinimum(1)
        self.sldCartSpeedValue.setMaximum(1000)
        self.sldCartSpeedValue.setOrientation(QtCore.Qt.Horizontal)
        self.sldCartSpeedValue.setObjectName("sldCartSpeedValue")
        self.lblCartIncDecValue = QtWidgets.QLabel(self.tab_2)
        self.lblCartIncDecValue.setGeometry(QtCore.QRect(180, 270, 21, 20))
        self.lblCartIncDecValue.setObjectName("lblCartIncDecValue")
        self.sldCartIncDecValue = QtWidgets.QSlider(self.tab_2)
        self.sldCartIncDecValue.setGeometry(QtCore.QRect(20, 290, 251, 22))
        self.sldCartIncDecValue.setMinimum(1)
        self.sldCartIncDecValue.setMaximum(25)
        self.sldCartIncDecValue.setOrientation(QtCore.Qt.Horizontal)
        self.sldCartIncDecValue.setObjectName("sldCartIncDecValue")
        self.lblCartSpeedValue = QtWidgets.QLabel(self.tab_2)
        self.lblCartSpeedValue.setGeometry(QtCore.QRect(140, 10, 21, 20))
        self.lblCartSpeedValue.setObjectName("lblCartSpeedValue")
        self.lblCartIncDec = QtWidgets.QLabel(self.tab_2)
        self.lblCartIncDec.setGeometry(QtCore.QRect(35, 270, 141, 20))
        self.lblCartIncDec.setObjectName("lblCartIncDec")
        self.lblCartSpeed = QtWidgets.QLabel(self.tab_2)
        self.lblCartSpeed.setGeometry(QtCore.QRect(40, 10, 91, 20))
        self.lblCartSpeed.setObjectName("lblCartSpeed")
        self.tabJogging.addTab(self.tab_2, "")
        self.lblAngle1 = QtWidgets.QLabel(self.centralwidget)
        self.lblAngle1.setGeometry(QtCore.QRect(560, 400, 50, 23))
        self.lblAngle1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAngle1.setObjectName("lblAngle1")
        self.lblAngle2 = QtWidgets.QLabel(self.centralwidget)
        self.lblAngle2.setGeometry(QtCore.QRect(610, 400, 50, 23))
        self.lblAngle2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAngle2.setObjectName("lblAngle2")
        self.lblAngle3 = QtWidgets.QLabel(self.centralwidget)
        self.lblAngle3.setGeometry(QtCore.QRect(660, 400, 50, 23))
        self.lblAngle3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAngle3.setObjectName("lblAngle3")
        self.lblAngle4 = QtWidgets.QLabel(self.centralwidget)
        self.lblAngle4.setGeometry(QtCore.QRect(710, 400, 50, 23))
        self.lblAngle4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAngle4.setObjectName("lblAngle4")
        self.lblAngle5 = QtWidgets.QLabel(self.centralwidget)
        self.lblAngle5.setGeometry(QtCore.QRect(760, 400, 50, 23))
        self.lblAngle5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAngle5.setObjectName("lblAngle5")
        self.lblAngle6 = QtWidgets.QLabel(self.centralwidget)
        self.lblAngle6.setGeometry(QtCore.QRect(810, 400, 50, 23))
        self.lblAngle6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAngle6.setObjectName("lblAngle6")
        self.lblCart1 = QtWidgets.QLabel(self.centralwidget)
        self.lblCart1.setGeometry(QtCore.QRect(560, 430, 50, 23))
        self.lblCart1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblCart1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCart1.setObjectName("lblCart1")
        self.lblCart2 = QtWidgets.QLabel(self.centralwidget)
        self.lblCart2.setGeometry(QtCore.QRect(610, 430, 50, 23))
        self.lblCart2.setMinimumSize(QtCore.QSize(0, 0))
        self.lblCart2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblCart2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCart2.setObjectName("lblCart2")
        self.lblCart3 = QtWidgets.QLabel(self.centralwidget)
        self.lblCart3.setGeometry(QtCore.QRect(660, 430, 50, 23))
        self.lblCart3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCart3.setObjectName("lblCart3")
        self.lblCart4 = QtWidgets.QLabel(self.centralwidget)
        self.lblCart4.setGeometry(QtCore.QRect(710, 430, 50, 23))
        self.lblCart4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCart4.setObjectName("lblCart4")
        self.lblCart5 = QtWidgets.QLabel(self.centralwidget)
        self.lblCart5.setGeometry(QtCore.QRect(760, 430, 50, 23))
        self.lblCart5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCart5.setObjectName("lblCart5")
        self.lblCart6 = QtWidgets.QLabel(self.centralwidget)
        self.lblCart6.setGeometry(QtCore.QRect(810, 430, 50, 23))
        self.lblCart6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblCart6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCart6.setObjectName("lblCart6")
        self.lblAnglesAll = QtWidgets.QLabel(self.centralwidget)
        self.lblAnglesAll.setGeometry(QtCore.QRect(510, 410, 47, 13))
        self.lblAnglesAll.setObjectName("lblAnglesAll")
        self.lblCoordAll = QtWidgets.QLabel(self.centralwidget)
        self.lblCoordAll.setGeometry(QtCore.QRect(510, 430, 47, 16))
        self.lblCoordAll.setObjectName("lblCoordAll")
        self.pbResumeMotion = QtWidgets.QPushButton(self.centralwidget)
        self.pbResumeMotion.setGeometry(QtCore.QRect(790, 100, 90, 23))
        self.pbResumeMotion.setMinimumSize(QtCore.QSize(75, 0))
        self.pbResumeMotion.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbResumeMotion.setObjectName("pbResumeMotion")
        self.pbPauseMotion = QtWidgets.QPushButton(self.centralwidget)
        self.pbPauseMotion.setGeometry(QtCore.QRect(790, 70, 90, 23))
        self.pbPauseMotion.setMinimumSize(QtCore.QSize(90, 0))
        self.pbPauseMotion.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbPauseMotion.setObjectName("pbPauseMotion")
        self.pbMove = QtWidgets.QPushButton(self.centralwidget)
        self.pbMove.setGeometry(QtCore.QRect(760, 580, 90, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbMove.sizePolicy().hasHeightForWidth())
        self.pbMove.setSizePolicy(sizePolicy)
        self.pbMove.setObjectName("pbMove")
        self.pbResetError = QtWidgets.QPushButton(self.centralwidget)
        self.pbResetError.setGeometry(QtCore.QRect(760, 490, 90, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbResetError.sizePolicy().hasHeightForWidth())
        self.pbResetError.setSizePolicy(sizePolicy)
        self.pbResetError.setObjectName("pbResetError")
        self.pbClearMotion = QtWidgets.QPushButton(self.centralwidget)
        self.pbClearMotion.setGeometry(QtCore.QRect(790, 40, 90, 23))
        self.pbClearMotion.setMinimumSize(QtCore.QSize(90, 0))
        self.pbClearMotion.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pbClearMotion.setObjectName("pbClearMotion")
        self.textedit_log = QtWidgets.QTextEdit(self.centralwidget)
        self.textedit_log.setGeometry(QtCore.QRect(10, 10, 481, 431))
        self.textedit_log.setReadOnly(True)
        self.textedit_log.setObjectName("textedit_log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabJogging.setCurrentIndex(1)
        self.sldAngIncDecValue.valueChanged['int'].connect(self.lblAngIncDecValue.setNum)
        self.sldAngSpeedValue.valueChanged['int'].connect(self.lblAngSpeedValue.setNum)
        self.sldCartSpeedValue.valueChanged['int'].connect(self.lblCartSpeedValue.setNum)
        self.sldCartIncDecValue.valueChanged['int'].connect(self.lblCartIncDecValue.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbUp.setText(_translate("MainWindow", "Up"))
        self.pbDown.setText(_translate("MainWindow", "Down"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "aaaaa"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.lblAngSpeedValue.setText(_translate("MainWindow", "1"))
        self.lblAngSpeed.setText(_translate("MainWindow", "Angular speed  ="))
        self.lblAngIncDec.setText(_translate("MainWindow", "Angle increment value ="))
        self.lblAngIncDecValue.setText(_translate("MainWindow", "1"))
        self.lEditAngle6.setText(_translate("MainWindow", "0"))
        self.pbTheta2_dec.setText(_translate("MainWindow", "-"))
        self.lEditAngle1.setText(_translate("MainWindow", "0"))
        self.lEditAngle5.setText(_translate("MainWindow", "0"))
        self.pbTheta1_inc.setText(_translate("MainWindow", "+"))
        self.lEditAngle4.setText(_translate("MainWindow", "0"))
        self.pbTheta3_inc.setText(_translate("MainWindow", "+"))
        self.lEditAngle3.setText(_translate("MainWindow", "0"))
        self.lEditAngle2.setText(_translate("MainWindow", "0"))
        self.pbTheta4_inc.setText(_translate("MainWindow", "+"))
        self.pbTheta6_dec.setText(_translate("MainWindow", "-"))
        self.pbTheta3_dec.setText(_translate("MainWindow", "-"))
        self.pbTheta6_inc.setText(_translate("MainWindow", "+"))
        self.pbTheta2_inc.setText(_translate("MainWindow", "+"))
        self.pbTheta1_dec.setText(_translate("MainWindow", "-"))
        self.pbTheta4_dec.setText(_translate("MainWindow", "-"))
        self.pbTheta5_dec.setText(_translate("MainWindow", "-"))
        self.pbTheta5_inc.setText(_translate("MainWindow", "+"))
        self.lbl_t6.setText(_translate("MainWindow", "θ6"))
        self.lbl_t3.setText(_translate("MainWindow", "θ3"))
        self.lbl_t4.setText(_translate("MainWindow", "θ4"))
        self.lbl_t2.setText(_translate("MainWindow", "θ2"))
        self.lbl_t1.setText(_translate("MainWindow", "θ1"))
        self.lbl_t5.setText(_translate("MainWindow", "θ5"))
        self.tabJogging.setTabText(self.tabJogging.indexOf(self.tab_1), _translate("MainWindow", "Joints"))
        self.lEditCart6.setText(_translate("MainWindow", "0"))
        self.lEditCart1.setText(_translate("MainWindow", "0"))
        self.lEditCart4.setText(_translate("MainWindow", "0"))
        self.lEditCart3.setText(_translate("MainWindow", "0"))
        self.lEditCart2.setText(_translate("MainWindow", "0"))
        self.lEditCart5.setText(_translate("MainWindow", "0"))
        self.lbl_z.setText(_translate("MainWindow", "z"))
        self.lbl_x.setText(_translate("MainWindow", "x"))
        self.lbl_Y.setText(_translate("MainWindow", "Y"))
        self.lbl_y.setText(_translate("MainWindow", "y"))
        self.lbl_X.setText(_translate("MainWindow", "X"))
        self.lbl_Z.setText(_translate("MainWindow", "Z"))
        self.pbCart6_inc.setText(_translate("MainWindow", "+"))
        self.pbCart2_inc.setText(_translate("MainWindow", "+"))
        self.pbCart1_inc.setText(_translate("MainWindow", "+"))
        self.pbCart3_inc.setText(_translate("MainWindow", "+"))
        self.pbCart4_inc.setText(_translate("MainWindow", "+"))
        self.pbCart5_inc.setText(_translate("MainWindow", "+"))
        self.pbCart6_dec.setText(_translate("MainWindow", "-"))
        self.pbCart5_dec.setText(_translate("MainWindow", "-"))
        self.pbCart3_dec.setText(_translate("MainWindow", "-"))
        self.pbCart1_dec.setText(_translate("MainWindow", "-"))
        self.pbCart2_dec.setText(_translate("MainWindow", "-"))
        self.pbCart4_dec.setText(_translate("MainWindow", "-"))
        self.lblCartIncDecValue.setText(_translate("MainWindow", "1"))
        self.lblCartSpeedValue.setText(_translate("MainWindow", "1"))
        self.lblCartIncDec.setText(_translate("MainWindow", "Cartesian increment value ="))
        self.lblCartSpeed.setText(_translate("MainWindow", "Cartesian speed  ="))
        self.tabJogging.setTabText(self.tabJogging.indexOf(self.tab_2), _translate("MainWindow", "Cart"))
        self.lblAngle1.setText(_translate("MainWindow", "0.000"))
        self.lblAngle2.setText(_translate("MainWindow", "0.000"))
        self.lblAngle3.setText(_translate("MainWindow", "0.000"))
        self.lblAngle4.setText(_translate("MainWindow", "0.000"))
        self.lblAngle5.setText(_translate("MainWindow", "0.000"))
        self.lblAngle6.setText(_translate("MainWindow", "0.000"))
        self.lblCart1.setText(_translate("MainWindow", "0.000"))
        self.lblCart2.setText(_translate("MainWindow", "0.000"))
        self.lblCart3.setText(_translate("MainWindow", "0.000"))
        self.lblCart4.setText(_translate("MainWindow", "0.000"))
        self.lblCart5.setText(_translate("MainWindow", "0.000"))
        self.lblCart6.setText(_translate("MainWindow", "0.000"))
        self.lblAnglesAll.setText(_translate("MainWindow", "Angles"))
        self.lblCoordAll.setText(_translate("MainWindow", "Coord"))
        self.pbResumeMotion.setText(_translate("MainWindow", "ResumeMotion"))
        self.pbPauseMotion.setText(_translate("MainWindow", "PauseMotion"))
        self.pbMove.setText(_translate("MainWindow", "Move"))
        self.pbResetError.setText(_translate("MainWindow", "ResetError"))
        self.pbClearMotion.setText(_translate("MainWindow", "ClearMotion"))
        self.textedit_log.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))

